version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages

    docker:
      - image: circleci/node:9.7

    working_directory: ~/get-poop-done

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Update npm
          command: npm i -g npm@5.7

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Test
          command: npm test

      - run:
          name: Build
          command: npm run build

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              if [ "${DOMAIN}" ]; then
                echo "$DOMAIN" > build/CNAME
              fi
              cp -r .circleci 01-external-dependencies/.circleci
              git config --global user.email "$GH_EMAIL"
              git config --global user.name "$GH_NAME"
              NODE_DEBUG=gh-pages npm run deploy -- -m 'Automated build'
            else
              echo "Not master branch so not deploying"
            fi
